"""added currency and unit to docket

Revision ID: c2145e801ef9
Revises: 982f0871f8bd
Create Date: 2026-01-17 22:35:56.319128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2145e801ef9'
down_revision: Union[str, None] = '982f0871f8bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('docket_items', sa.Column('unit', sa.String(length=20), nullable=True))
    op.add_column('dockets', sa.Column('currency', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dockets', 'currency')
    op.drop_column('docket_items', 'unit')
    # ### end Alembic commands ###
